# .github/workflows/download-rust-server.yml
name: Download Rust Server

on:
  workflow_dispatch:   # manual trigger

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download install script
        run: |
          # Download the official install_rust_server.sh from GitHub
          curl -sL https://raw.githubusercontent.com/publicrust/rust-server-setup/main/install_rust_server.sh \
            -o install_rust_server.sh
          # Make the script executable
          chmod +x install_rust_server.sh

      - name: Install Rust server
        run: |
          # Execute the install script to download and unpack the server
          ./install_rust_server.sh

      - name: Verify installation
        run: |
          # Print confirmation message
          echo "Rust server installed. Server file structure:"
          # Recursively list files under the 'server/' directory
          ls -R server
